feature/init-firewall
crypto-pepe/firewall-cloudflare-executor pull request #1
Opened 2022-05-12 17:48 UTC by citizensix

2022-05-17 16:57 UTC, stuffy-idler requested changes

2022-05-17 16:57 UTC, stuffy-idler commented on src/main.rs
> +const DEFAULT_CFG_PATH: &str = "./config.yaml";
I suggest to move to configuration module

2022-05-17 16:57 UTC, stuffy-idler commented on src/main.rs
> +        configuration::get_config(DEFAULT_CFG_PATH).expect("Failed to read configuration.");
I suggest to export `get_config` or `load` function from `configuration`, which will see to the needed path, parse the config file and return configuration

2022-05-17 16:57 UTC, stuffy-idler commented on src/startup.rs
> +        let port = listener.local_addr().unwrap().port();
`build` returns `Result`, therefore you can not to `unwrap`, but match whether it's Ok or Err, or use `?`

2022-05-17 16:57 UTC, stuffy-idler commented on src/configuration.rs
> +    pepe_config::load(path, config::FileFormat::Json)
Whether it should be Json or Yaml?

2022-05-19 15:10 UTC, stuffy-idler requested changes

2022-05-19 15:10 UTC, stuffy-idler commented on Cargo.toml
> +pepe-config = "0.0.2"
`pepe-config` is now v0.0.3 and it exports all what you need to get rid of `config` crate

2022-05-24 12:44 UTC, stuffy-idler requested changes

2022-05-24 12:44 UTC, stuffy-idler commented on src/handlers/ban.rs
> +use crate::cloudflare_client::CloudflareClient;
I suggest to create service (as `BanHammer` in `firewall-executor`) which will implement all logic about ban/unban (working will pg), dry run mode

Therefore http handler `ban` will take this service as dependency an will just call its methods

2022-05-26 16:05 UTC, stuffy-idler requested changes

2022-05-26 16:05 UTC, stuffy-idler commented on src/executor/op.rs
> +        req: web::Json<handlers::models::BlockRequest>,
Better to take not http request, but appropriate entity

2022-05-30 14:10 UTC, stuffy-idler requested changes

2022-05-30 14:10 UTC, stuffy-idler commented on src/executor/op.rs
> +    db_pool: Pool<DieselConnectionManager<DieselConnection<PgConnection>>>,
I guess `DieselConnectionManager<DieselConnection<PgConnection>>` can be type-aliased to clearer code

2022-05-30 14:10 UTC, stuffy-idler commented on src/executor/op.rs
> +        nongrata.rule_id = rule_id;
Looks like `nongrata` can be created after `self.client.restrict_rule` call, therefore it can be immutable together with the `rule_id`

2022-05-30 14:10 UTC, stuffy-idler commented on src/executor/op.rs
> +            match self.db_pool.get().await {
rust way is to use `map_err` with question mark instead of pattern matching

2022-05-30 14:10 UTC, stuffy-idler commented on src/executor/dry.rs
> +        match block_request.target.ip.clone() {
I suggest to rewrite is using `form_firewall_rule_expression`

2022-05-30 14:10 UTC, stuffy-idler commented on src/executor/dry.rs
> +        match unblock_request.target.ip.clone() {
I suggest to rewrite is using `form_firewall_rule_expression`

2022-05-30 14:10 UTC, stuffy-idler commented on src/cloudflare_client.rs
> +            c: Client::builder()
I suggest to rename it to `client` or `http_client` to be more descriptive

2022-05-31 13:57 UTC, stuffy-idler requested changes

2022-05-31 13:57 UTC, stuffy-idler commented on src/executor/models.rs
> +pub struct BlockResponse {
It doesn't used, can be dropped

2022-05-31 13:57 UTC, stuffy-idler commented on src/executor/op.rs
> +        let conn: PooledConnection<DieselConnectionManager<DieselConnection<PgConnection>>> = self
`PooledConnection<DbConn>`

2022-05-31 13:57 UTC, stuffy-idler commented on src/executor/op.rs
> +        let rule = unblock_request.clone();
I guess it's unnecessary

2022-05-31 13:57 UTC, stuffy-idler commented on src/handlers/bans.rs
> +pub async fn ban_according_to_mode(
Should take `X-Analyzer-Id` header value and save it along with block request data

2022-06-02 09:32 UTC, stuffy-idler requested changes

2022-06-02 09:32 UTC, stuffy-idler commented on src/executor/dry.rs
> +            Some(rule),
What is the reason to wrap rule into `Some`?

2022-06-02 09:32 UTC, stuffy-idler commented on src/executor/dry.rs
> +        info!("gonna apply UNBAN rule: {:?}", Some(rule));
What is the reason to wrap rule into `Some`?

2022-06-02 09:32 UTC, stuffy-idler commented on src/executor/dry.rs
> +impl Default for ExecutorServiceDry {
I guess it can be via the derive macro

2022-06-02 09:32 UTC, stuffy-idler commented on src/executor/op.rs
> +        if let Err(e) = diesel::insert_into(schema::nongratas::table)
The common way to handle an error is using `map_err` and `?`:
```rust
diesel::insert_into(schema::nongratas::table)
  .values(nongrata)
  .execute(&*conn)
  .map_err(|e| errors::wrap_err(e.into()))?;

Ok(())
```

2022-06-02 09:32 UTC, stuffy-idler commented on src/executor/op.rs
> +            return Err(errors::wrap_err(e.into()));
Is it transformed to `ServerError::DbError`?

2022-06-02 09:32 UTC, stuffy-idler commented on src/cloudflare_client.rs
> +            .body(req)
Can it be done with `json` method of builder? It transforms request struct to JSON using serde and set appropriate content-type header

2022-06-02 09:32 UTC, stuffy-idler commented on src/cloudflare_client.rs
> +        let value = match resp.result.first() {
It can be rewritten as:
```rust
let value = resp.result.first()
  .ok_or(ServerError::WrappedErr {
    cause: "bad response".to_string(),
  }.into())?;
```

2022-06-02 09:32 UTC, stuffy-idler commented on src/cloudflare_client.rs
> +        Ok(value.id.clone())
Whether it should be cloned?

2022-06-03 13:29 UTC, citizensix commented on src/cloudflare_client.rs
> +        Ok(value.id.clone())
Yep bc of ```cannot move out of `value.id` which is behind a shared reference```

2022-06-07 09:30 UTC, stuffy-idler requested changes

2022-06-07 09:30 UTC, stuffy-idler commented on src/cloudflare_client.rs
> +        let req = serde_json::to_string(&models::FirewallRuleRequest {
It's unnecessary, because of `FirewallRuleRequest` derives `Serialize`, which add an ability to be automatically converted to response under-the-hood of `.json()` call

2022-06-07 09:30 UTC, stuffy-idler commented on src/cloudflare_client.rs
> +        let value = resp.result.first().ok_or::<ServerError>(
I guess checking the `success` field of response will be enough

2022-06-07 09:30 UTC, stuffy-idler commented on src/cloudflare_client.rs
> +        Ok(value.id.clone())
Got it

2022-06-08 08:11 UTC, stuffy-idler requested changes

2022-06-08 08:11 UTC, stuffy-idler commented on Cargo.toml
> +diesel = { version = "1.4", features = ["r2d2", "postgres", "chrono"], default-features = false }
Is `r2d2` used?

2022-06-08 08:11 UTC, stuffy-idler commented on Cargo.toml
> +lazy_static = "1.4.0"
Is it used?

2022-06-08 08:11 UTC, stuffy-idler commented on Cargo.toml
> +dotenv = "0.15.0"
Is it used?

2022-06-08 08:11 UTC, stuffy-idler commented on src/errors.rs
> +pub fn wrap_client_err(e: anyhow::Error) -> ServerError {
Is it used?

2022-06-08 08:11 UTC, stuffy-idler commented on src/errors.rs
> +pub fn wrap_err(e: anyhow::Error) -> ServerError {
Is it used?

2022-06-08 08:11 UTC, stuffy-idler commented on src/executor/mod.rs
> +pub mod dry;
I suggest to name it `dry_run` – I think it will be clearer

2022-06-08 09:35 UTC, stuffy-idler approved these changes

2022-06-08 09:44 UTC, merged