Fix/#13 status code
crypto-pepe/firewall-cloudflare-executor pull request #15
Opened 2022-06-23 08:15 UTC by citizensix

2022-06-23 15:08 UTC, stuffy-idler requested changes

2022-06-23 15:08 UTC, stuffy-idler commented on src/executor/op_run.rs
> +                .filter(schema::nongratas::restriction_value.eq(firewall_rule.clone()));
Whether `firewall_rule` should be cloned? Can it be used by ref?

2022-06-23 15:08 UTC, stuffy-idler commented on src/executor/op_run.rs
> +            .filter(schema::nongratas::restriction_value.eq(firewall_rule.clone()))
It should be also filtered for requested `analyzer_id`. Moreover there can only one rule_id for pair `target + analyzer_id`

2022-06-23 15:08 UTC, stuffy-idler commented on src/executor/op_run.rs
> +            if block_request.ttl == 0 {
I guess it should be moved to API `handler`

2022-06-23 15:08 UTC, stuffy-idler commented on src/executor/op_run.rs
>          let firewall_rule =
At 39 line there is `block_request` cloning – it's unnecessary and can be dropped. `info` and another macros takes parameters by ref

2022-06-24 08:29 UTC, stuffy-idler approved these changes

2022-06-24 13:07 UTC, citizensix commented
> @stuffy-idler Don't work! For all requests **/bans** there is response:
> 
> ```
> {
>     "code": 500,
>     "reason": "NotFound",
>     "details": null
> }
> ```
The problem was that `first()` treats empty rows as an error unlike `load()` so I've changed this

2022-06-24 13:59 UTC, stuffy-idler commented
@Rabid-Squirrel

2022-06-24 14:00 UTC, stuffy-idler approved these changes

2022-06-27 12:34 UTC, stuffy-idler approved these changes

2022-06-28 14:55 UTC, stuffy-idler commented
@citizensix PR can be merged

2022-06-29 08:02 UTC, merged