Feature/executor cloudflare invalidation
crypto-pepe/firewall-cloudflare-executor pull request #7
Opened 2022-06-01 14:29 UTC by citizensix

2022-06-06 14:38 UTC, horny-manul requested changes

2022-06-06 14:38 UTC, horny-manul commented on src/executor/dry.rs
> +            "gonna apply BAN rule: {:?}\n Analyzer: {:?}",
Try use more formal language

2022-06-06 14:38 UTC, horny-manul commented on src/executor/dry.rs
> +        if rule.is_none() {
`or_else` or something similar?

2022-06-06 15:39 UTC, horny-manul requested changes

2022-06-06 15:39 UTC, horny-manul commented on src/executor/op.rs
> +        if block_request.ttl == 0 {
Add #[serde(default)] to struct

2022-06-10 11:27 UTC, horny-manul requested changes

2022-06-10 11:27 UTC, horny-manul commented on src/cloudflare_client.rs
> +    pub async fn create_block_rule(
What about adding `#[tracing::instrument()]` to functions? Not only that one

2022-06-10 11:27 UTC, horny-manul commented on src/cloudflare_client.rs
> +            header::HeaderValue::from_str(format!("Bearer {}", token.as_str()).as_str())
Maybe `format!("Bearer {}", token.as_str()).parse().unwrap()` like that instead of `header::HeaderValue::from_str(format!("Bearer {}", token.as_str()).as_str())`?

2022-06-10 11:27 UTC, horny-manul commented on src/cloudflare_client.rs
> +            .post(self.base_api_url.to_owned().add(path.as_str()))
Maybe use `foramt!("{}{}")`?

2022-06-10 11:27 UTC, horny-manul commented on src/cloudflare_client.rs
> +            .delete(self.base_api_url.to_owned().add(path.as_str()))
Same as above

2022-06-10 11:27 UTC, horny-manul commented on src/errors.rs
> +    ClietnError(#[from] reqwest::Error),
typo `Client`

2022-06-10 11:27 UTC, horny-manul commented on src/errors.rs
>                  HttpResponse::Ok().json(handlers::models::ExecutorResponse::no_target())
Bad request

2022-06-10 11:27 UTC, horny-manul commented on src/errors.rs
> +                HttpResponse::Ok().json(handlers::models::ExecutorResponse::no_ttl())
Bad request

2022-06-10 11:27 UTC, horny-manul commented on src/errors.rs
> +                HttpResponse::Ok().json(handlers::models::ExecutorResponse::wrong_log_level())
Bad request

2022-06-10 11:27 UTC, horny-manul commented on src/errors.rs
> +                HttpResponse::Ok().json(handlers::models::ExecutorResponse::no_dry_run_status())
Bad request

2022-06-10 11:27 UTC, horny-manul commented on src/executor/op_run.rs
> +        let handlers = rule_ids
handles maybe?

2022-06-10 12:28 UTC, citizensix commented on src/cloudflare_client.rs
> +            header::HeaderValue::from_str(format!("Bearer {}", token.as_str()).as_str())
nope, not going to `unwrap` in the actual code

2022-06-10 13:31 UTC, horny-manul requested changes

2022-06-10 13:31 UTC, horny-manul commented on src/errors.rs
> +                HttpResponse::InternalServerError().json(source.to_string())
Will that really be sent like json? Or it will be sent like plain text with application/json header?

2022-06-10 13:31 UTC, horny-manul commented on src/executor/dry_run.rs
> +        let rule = models::form_firewall_rule_expression(ip.as_ref(), ua.as_ref());
This function can be rewriten to accept `Option<String>` and it will not break anything

2022-06-10 13:31 UTC, horny-manul commented on src/executor/op_run.rs
> +                diesel::delete(schema::nongratas::table.filter(schema::nongratas::rule_id.eq(id)))
If it fails, is that ok, that some rules will be deleted and some will not? I suggest to delete it inside transaction if possible

2022-06-10 13:48 UTC, citizensix commented on src/errors.rs
>                  HttpResponse::InternalServerError().json(source.to_string())
Answered

2022-06-10 13:56 UTC, citizensix commented on src/executor/op_run.rs
> +                diesel::delete(schema::nongratas::table.filter(schema::nongratas::rule_id.eq(id)))
I guess there is no need to perform atomic operation inside transaction

2022-06-10 14:02 UTC, horny-manul commented
lgtm

2022-06-10 14:02 UTC, horny-manul approved these changes

2022-06-14 09:59 UTC, stuffy-idler requested changes

2022-06-14 09:59 UTC, stuffy-idler commented on migrations/2022-05-13-095358_create_nongratas/up.sql
> +on events using btree (restriction_value, rule_id);
There is not table with name `events`, but `nongratas`.

2022-06-14 09:59 UTC, stuffy-idler commented on migrations/2022-05-13-095358_create_nongratas/up.sql
> +create index concurrently "restriction_value_rule_id_index"
Quotes around index name is unnecessary

2022-06-14 09:59 UTC, stuffy-idler commented on migrations/2022-05-13-095358_create_nongratas/up.sql
> +create index concurrently "restriction_value_rule_id_index"
Index commonly named with suffix `idx` instead of `index`

2022-06-14 09:59 UTC, stuffy-idler commented on src/main.rs
> +    let db_conn_string = configuration.clone().db.pg_conn_string();
I suggest to extract pool building to separate module

2022-06-14 09:59 UTC, stuffy-idler commented on src/models.rs
> +pub type DbConn = DieselConnectionManager<DieselConnection<PgConnection>>;
Commonly in rust tests are in last place of module structure, and static with types – in first one

2022-06-14 09:59 UTC, stuffy-idler commented on src/configuration.rs
> +    pub invalidation_timeout_string: DurationString,
I guess `_string` suffix is unnecessary

2022-06-14 09:59 UTC, stuffy-idler commented on src/invalidator/service.rs
> +    timeout_sec: Duration,
I guess `_sec` is unnecessary suffix

2022-06-14 16:03 UTC, stuffy-idler commented on src/models.rs
> +pub type DbConn = DieselConnectionManager<DieselConnection<PgConnection>>;
I guess `pool.rs` is better place for this type

2022-06-14 16:37 UTC, stuffy-idler approved these changes

2022-06-15 07:52 UTC, merged